load("//tools/build_defs/oss:soloader_defs.bzl", "fb_java_library")

oncall("android_systems_reliability")

fb_java_library(
    name = "nativeloader",
    srcs = glob([
        "*.java",
    ]),
    visibility = [
        "PUBLIC",
    ],
)
